### ISSUE TITLE
svg transform loader：when @import a.css in b.css ,fill?#XXX in a.css will not be processed to when @import a.css in b.css ,?fill=#XXX in a.css will not be processed

### ISSUE THREAD

**Issue by vivitan** [kisenka/svg-mixer#30]

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by vivitan** [comment]
https://github.com/vivitan/svg-mix-demo

**Comment by kisenka** [comment]
@vivitan sorry for the delay, your issue is pretty hard to investigate. 2 moments here:
1. css-loader by default won't apply preceding loaders to `@imported` resources. In your case `@import "tem.css";` will not be processed by `svg-transform-loader/encode-query`. To make it works you should set [`importLoaders`](https://github.com/webpack-contrib/css-loader#importloaders) option of css-loader to `1` (`0` by default).
2. You're using file-loader to further SVG processing, but file pattern `[path][name].[ext]` always produces vinyls.svg. To create separate files on each `fill=` request you should add `[hash]` token to file pattern. 

Both moments I'll add to readme, thanks!

**Comment by vivitan** [comment]
@kisenka thank u
